// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYERDATA_EATER_PLAYERDATA_H_
#define FLATBUFFERS_GENERATED_PLAYERDATA_EATER_PLAYERDATA_H_

#include "flatbuffers/flatbuffers.h"

namespace Eater {
namespace PlayerData {

struct Vec3;

struct Player;
struct PlayerBuilder;

struct PlayerList;
struct PlayerListBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct Player FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PlayerBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IDENTIFIER = 4,
    VT_POS = 6,
    VT_MOV_VECTOR = 8,
    VT_HP = 10,
    VT_ANIMATION_TYPE = 12
  };
  int16_t identifier() const {
    return GetField<int16_t>(VT_IDENTIFIER, 0);
  }
  const Eater::PlayerData::Vec3 *pos() const {
    return GetStruct<const Eater::PlayerData::Vec3 *>(VT_POS);
  }
  const Eater::PlayerData::Vec3 *mov_vector() const {
    return GetStruct<const Eater::PlayerData::Vec3 *>(VT_MOV_VECTOR);
  }
  uint32_t hp() const {
    return GetField<uint32_t>(VT_HP, 0);
  }
  uint32_t animation_type() const {
    return GetField<uint32_t>(VT_ANIMATION_TYPE, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_IDENTIFIER) &&
           VerifyField<Eater::PlayerData::Vec3>(verifier, VT_POS) &&
           VerifyField<Eater::PlayerData::Vec3>(verifier, VT_MOV_VECTOR) &&
           VerifyField<uint32_t>(verifier, VT_HP) &&
           VerifyField<uint32_t>(verifier, VT_ANIMATION_TYPE) &&
           verifier.EndTable();
  }
};

struct PlayerBuilder {
  typedef Player Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_identifier(int16_t identifier) {
    fbb_.AddElement<int16_t>(Player::VT_IDENTIFIER, identifier, 0);
  }
  void add_pos(const Eater::PlayerData::Vec3 *pos) {
    fbb_.AddStruct(Player::VT_POS, pos);
  }
  void add_mov_vector(const Eater::PlayerData::Vec3 *mov_vector) {
    fbb_.AddStruct(Player::VT_MOV_VECTOR, mov_vector);
  }
  void add_hp(uint32_t hp) {
    fbb_.AddElement<uint32_t>(Player::VT_HP, hp, 0);
  }
  void add_animation_type(uint32_t animation_type) {
    fbb_.AddElement<uint32_t>(Player::VT_ANIMATION_TYPE, animation_type, 0);
  }
  explicit PlayerBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Player> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Player>(end);
    return o;
  }
};

inline flatbuffers::Offset<Player> CreatePlayer(
    flatbuffers::FlatBufferBuilder &_fbb,
    int16_t identifier = 0,
    const Eater::PlayerData::Vec3 *pos = 0,
    const Eater::PlayerData::Vec3 *mov_vector = 0,
    uint32_t hp = 0,
    uint32_t animation_type = 0) {
  PlayerBuilder builder_(_fbb);
  builder_.add_animation_type(animation_type);
  builder_.add_hp(hp);
  builder_.add_mov_vector(mov_vector);
  builder_.add_pos(pos);
  builder_.add_identifier(identifier);
  return builder_.Finish();
}

struct PlayerList FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PlayerListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PLAYERS = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<Eater::PlayerData::Player>> *players() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Eater::PlayerData::Player>> *>(VT_PLAYERS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PLAYERS) &&
           verifier.VerifyVector(players()) &&
           verifier.VerifyVectorOfTables(players()) &&
           verifier.EndTable();
  }
};

struct PlayerListBuilder {
  typedef PlayerList Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_players(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Eater::PlayerData::Player>>> players) {
    fbb_.AddOffset(PlayerList::VT_PLAYERS, players);
  }
  explicit PlayerListBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<PlayerList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<PlayerList>(end);
    return o;
  }
};

inline flatbuffers::Offset<PlayerList> CreatePlayerList(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Eater::PlayerData::Player>>> players = 0) {
  PlayerListBuilder builder_(_fbb);
  builder_.add_players(players);
  return builder_.Finish();
}

inline flatbuffers::Offset<PlayerList> CreatePlayerListDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<Eater::PlayerData::Player>> *players = nullptr) {
  auto players__ = players ? _fbb.CreateVector<flatbuffers::Offset<Eater::PlayerData::Player>>(*players) : 0;
  return Eater::PlayerData::CreatePlayerList(
      _fbb,
      players__);
}

}  // namespace PlayerData
}  // namespace Eater

#endif  // FLATBUFFERS_GENERATED_PLAYERDATA_EATER_PLAYERDATA_H_
